apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mushop-secret-provider
  namespace: mushop
spec:
  provider: oci
  parameters:
    vaultId: ocid1.vault.oc1.eu-frankfurt-1.entn3qu7aadqm.abtheljtuxvmqwrhtbugqe7njkt5mx25og7ol32etxqahvunsn4ng6m3foba
    #${vault_ocid}
    authType: instance  # Assuming instance principal is used
    secrets: |
      - name: oadb-admin
      - name: oadb-wallet
      - name: oadb-connection
